# Tarea 2 
Paula Cintron 20160090

## Instrucciones 

1. Crear un tensor de list(range(9)) e indicar cual es el size, offset, y strides
    2. Crear un tensor b = a.view(3, 3). Cual es el valor de b[1, 1]?
    3. crear un tensor c = b[1:, 1:]. Cual es el size, offset, strides?
4. Escogan una operacion matematica como cosine o sqrt. Hay una funcion correspondiente en PyTorch?
5. Existe una version de esa operacion que opera in-place?
6. Crear un tensor 2D y luego agregar una dimension de tamanio 1 insertada en la dimension 0.
7. Eliminar la dimension extra que agrego en el tensor previo.
8. Crear un tensor aleatorio de forma $5x3$ en el intervalo $[3,7)$
9. Crear un tensor con valores de una distribucion normal ($\mu=0, \sigma=1$)
10. Recuperar los indices de todos los elementos no cero en el tensor torch.Tensor([1,1,1,0,1]).
11. Crear un tensor aleatorio de forma (3,1) y luego apilar cuatro copias horizontalmente.
12. Retornar el producto batch matrix-matrix de dos matrices 3D: (a=torch.randn(3,4,5), b=torch.rand(3,5,4))
13. Retornar el producto batch matrix-matrix de una matriz 3D y una matriz 2D: (a=torch.rand(3,4,5), b=torch.rand(5,4)).

In [1]:
import torch 

### 1) crear un tensor de list(range(9)) e indicar cual es el size, offset, y strides

In [48]:
#Primero, cree una lista de numeros
b_list = list(range(9))

In [55]:
#convertir la lista a torch
b_torch= torch.tensor(b_list)
b_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
# Shape de b
b_torch.shape

torch.Size([9])

In [57]:
# Stride de b
b_torch.stride()

(1,)

In [71]:
# Offset storage
b_torch.storage_offset()

0

### 1.a Crear un tensor b = a.view(3, 3). Cual es el valor de b[1, 1]?

In [61]:
#Primero cree una lista y luego lo converti a torch
b= [[1,2,3],[4,5,6],[7,8,9]]
b = torch.tensor(b)
b

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [64]:
# Shape del tensor b
b.shape

(1,)

In [66]:
# Stride de b
b.stride()

(3, 1)

In [67]:
# Offset storage
b.storage_offset()

0

### 1.b crear un tensor c = b[1:, 1:]. Cual es el size, offset, strides?

In [74]:
#Cree una lista y luego convertirlo a torch
c=b[1:,1:]
c_torch=torch.tensor(c)
c_torch

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  This is separate from the ipykernel package so we can avoid doing imports until


tensor([[5, 6],
        [8, 9]])

In [76]:
# Size
c_torch.size()

torch.Size([2, 2])

In [77]:
# Shape
c_torch.shape

torch.Size([2, 2])

In [78]:
# Offset
c_torch.storage_offset()

0

## 2) Escogan una operacion matematica como cosine o sqrt. Hay una funcion correspondiente en PyTorch?

In [78]:
#Adding and substracting

#creating 2 torhces
#a_list= [[1,2],[3,4]]
#a=torch.tensor(a_list)
a=torch.Tensor(1,2)
a1= torch.randn(4)

#b_list=[[5,6],[7,8]]
#b= torch.tensor(b_list)
b= torch.Tensor(1,2)

In [7]:
#adding both torhces
a + b

tensor([[7.7012e+31, 6.7415e+22]])

In [75]:
# Mean 
m = torch.mean(a,1)
m

tensor([1.])

In [80]:
# Math operations: cosine 
math = torch.cos(a1)
math

tensor([ 0.9314, -0.4485,  0.8263,  0.7684])

### 3) Existe una version de esa operacion que opera in-place?

In [6]:
a.add(b)

tensor([[7.7012e+31, 6.7415e+22]])

### 4) Crear un tensor 2D y luego agregar una dimension de tamaño 1 insertada en la dimension 0.

In [24]:
#Creating a 2D tensor
a= torch.Tensor(1,2)
a.size()

torch.Size([1, 2])

In [27]:
# Add a new dimension using NONE 
a2= a[None,:,:]
a2.size()

torch.Size([1, 1, 2])

### 5) Eliminar la dimension extra que agrego en el tensor previo.

In [34]:
# I am reshaping or risezing the tensor to the preivous size. 
a3= a2.resize_(1,2)
a3.size()

torch.Size([1, 2])

### 6) Crear un tensor aleatorio de forma  5𝑥3 en el intervalo  [3,7])

In [42]:
# La funcon randint genera una distribucion aleatoria de numeros en el tensor con rango y tamaño de tensor. 
r= torch.randint(3,7,(5,3))
r.size()


torch.Size([5, 3])

In [43]:
r

tensor([[6, 3, 4],
        [5, 5, 6],
        [4, 3, 6],
        [3, 3, 3],
        [3, 3, 5]])

### 7) Crear un tensor con valores de una distribucion normal ( 𝜇=0,𝜎=1)

In [46]:
# Usar la funcion torch distribution normal. Loc es la media y scale la desviacion estandar 
n = torch.distributions.Normal(torch.tensor(0), torch.tensor(1))
n

Normal(loc: 0, scale: 1)

In [73]:
n1  = torch.rand(0)
n1

tensor([])

In [74]:
#funciton randn returns tensor filled with random numbers form a normal distribtion with mean 0 and variance 1
n2= torch.randn(4)
n2

tensor([ 0.2782,  2.8205, -0.2202, -1.3786])

### 8) Recuperar los indices de todos los elementos no cero en el tensor torch.Tensor([1,1,1,0,1]).


In [59]:
cero= torch.Tensor([1,1,1,0,1])
cero


In [62]:
print((cero==0).nonzero()[0])

tensor([3])


### 9) Crear un tensor aleatorio de forma (3,1) y luego apilar cuatro copias horizontalmente.


In [70]:
r= torch.rand(3,1)
r

tensor([[0.8674],
        [0.7092],
        [0.4922]])

In [86]:
#Function repeats the tensor along the dimensions specified.
r2 = r.repeat(2,4)
r2

tensor([[0.8674, 0.8674, 0.8674, 0.8674],
        [0.7092, 0.7092, 0.7092, 0.7092],
        [0.4922, 0.4922, 0.4922, 0.4922],
        [0.8674, 0.8674, 0.8674, 0.8674],
        [0.7092, 0.7092, 0.7092, 0.7092],
        [0.4922, 0.4922, 0.4922, 0.4922]])

### 10) Retornar el producto batch matrix-matrix de dos matrices 3D: (a=torch.randn(3,4,5), b=torch.rand(3,5,4))


In [87]:
#Creating the torches
a5=torch.randn(3,4,5)
b5=torch.rand(3,4,5)

In [88]:
# Restar las dos matrices 
a5-b5

tensor([[[ 0.1960, -1.5050, -0.0100, -2.5744, -1.0185],
         [-0.1501, -0.0238,  0.3386,  0.1691, -1.3602],
         [-0.1071, -2.2742, -0.7782,  0.0509, -0.8890],
         [-2.5310, -0.7090, -0.5810, -1.2899, -2.6423]],

        [[-0.4335,  1.0538, -0.4254, -2.7389,  1.2965],
         [-0.8366,  0.1010, -0.7307, -0.9753, -1.1483],
         [-0.6985, -2.9991,  0.3710, -0.0861, -1.1452],
         [ 0.0774, -1.2270, -0.2697, -0.4481, -0.0677]],

        [[-2.5996, -1.7429, -2.3128,  0.5400, -0.4719],
         [ 1.2690, -2.8205,  0.5606,  0.7982,  1.0084],
         [ 0.1838,  1.2480,  0.8224, -1.2485,  0.8685],
         [-2.9482,  0.4959, -2.0045, -1.0740,  0.0507]]])

### 11) Retornar el producto batch matrix-matrix de una matriz 3D y una matriz 2D: (a=torch.rand(3,4,5), b=torch.rand(5,4)).

In [93]:
# Restar las dos matrices de diferentes dimensiones no se puede
b6= torch.randn(5,4)
a5-b6